version: '3'
services:
  swagger:
    image: swaggerapi/swagger-editor
    ports:
      - '80:8080'
  mongodb:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
  mongo_seed:
    build: ./db-seed/
    links:
      - mongodb
  holiday_api:
    build: ./api/
    volumes:
      - ./api:/usr/src/app
    ports:
      - $API_PORT:$API_PORT
    links:
      - mongo_seed
      - mongodb
networks:
  webnet:
