# RESTClient plugin https://github.com/Huachao/vscode-restclient

POST http://localhost:3001/api/login
email: tom@holextra.com
password: password

###

POST http://localhost:3001/api/register
id: 1234
email: john@holextra.com
password: password
givenName: John
familyName: Solomon
about: I like space nships

###

PATCH http://localhost:3001/api/update
_id: 5e4b6871f5a6600007190813
id: 109
email: me@holextra.com
password: somethinghere
givenName: Johan
familyName: Solomon
about: I like television

###

DELETE http://localhost:3001/api/delete
_id: 5e4b7a7336f29e000879e948

###

GET http://localhost:3001/api/user
_id: 5e4b831234007d0007c5714a

###

GET http://localhost:3001/api/allusers